name: Build and Release Electron App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write # Grant permission to create releases

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Snapcraft (Linux only)
        run: sudo snap install snapcraft --classic
        if: runner.os == 'Linux'

      - name: Build Electron App
        run: npm run build:electron
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # You can still use the default token

      - name: Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist_electron/*
          draft: true